# Generated by Django 4.2.26 on 2025-12-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_instansi', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=255, unique=True)),
                ('no_seri_karpeg', models.CharField(blank=True, max_length=255, null=True)),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('pangkat', models.CharField(max_length=255)),
                ('golongan', models.CharField(max_length=255)),
                ('tmt_pangkat', models.DateField()),
                ('jabatan', models.CharField(max_length=255)),
                ('tmt_jabatan', models.DateField()),
                ('unit_kerja', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Penilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=255, unique=True)),
                ('no_seri_karpeg', models.CharField(blank=True, max_length=255, null=True)),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('pangkat', models.CharField(max_length=255)),
                ('golongan', models.CharField(max_length=255)),
                ('tmt_pangkat', models.DateField()),
                ('jabatan', models.CharField(max_length=255)),
                ('tmt_jabatan', models.DateField()),
                ('unit_kerja', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AngkaIntegrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_angka_integrasi', models.FloatField()),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='AK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_awal_penilaian', models.DateField()),
                ('tanggal_akhir_penilaian', models.DateField()),
                ('penilaian', models.CharField(max_length=255)),
                ('prosentase', models.IntegerField()),
                ('koefisien', models.FloatField()),
                ('jumlah_angka_kredit', models.FloatField()),
                ('tanggal_ditetapkan', models.DateField()),
                ('tempat_ditetapkan', models.CharField(max_length=255)),
                ('jenjang', models.CharField(max_length=255)),
                ('instansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.instansi')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai')),
                ('penilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.penilai')),
            ],
        ),
    ]
