# Generated by Django 4.2.27 on 2026-02-02 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_awal_penilaian', models.DateField(verbose_name='Tanggal Awal Penilaian')),
                ('tanggal_akhir_penilaian', models.DateField(verbose_name='Tanggal Akhir Penilaian')),
                ('jenis_kegiatan', models.CharField(max_length=255, verbose_name='Jenis Kegiatan Pendidikan')),
                ('tingkat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tingkat Pendidikan')),
                ('tanggal_pelaksanaan', models.DateField(verbose_name='Tanggal Pelaksanaan')),
                ('durasi_pelatihan', models.IntegerField(help_text='Durasi pelatihan dalam jam', verbose_name='Durasi Pelatihan (Jam)')),
                ('jumlah_angka_kredit', models.FloatField(verbose_name='Jumlah Angka Kredit')),
                ('tanggal_ditetapkan', models.DateField(verbose_name='Tanggal Ditentukan')),
                ('tempat_ditetapkan', models.CharField(max_length=255, verbose_name='Tempat Ditentukan')),
                ('nomor_sertifikat', models.CharField(max_length=255, unique=True, verbose_name='Nomor Sertifikat')),
                ('file_sertifikat', models.FileField(blank=True, null=True, upload_to='sertifikat_pendidikan/', verbose_name='File Sertifikat')),
                ('instansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.instansi', verbose_name='Instansi')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai', verbose_name='Pegawai')),
                ('penilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.penilai', verbose_name='Penilai')),
            ],
        ),
    ]
