# Generated by Django 4.2.27 on 2026-05-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_akpendidikan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ak',
            name='Nomor_AK',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor AK'),
        ),
    ]
