"""
Django settings for AppAk2 project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY', default='django-insecure-)))w*k!ve%=n*ck9+=$!45#26@b4+=2+si_jtw5asj-)=8_8-j')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pegawai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AppAk2.urls'


# settings.py
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,  # HARUS TRUE untuk load template dari app folders
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AppAk2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import os
from decouple import config, UndefinedValueError

# Check if we should use SQLite for initial migration
USE_SQLITE_FOR_MIGRATION = os.environ.get('USE_SQLITE_FOR_MIGRATION', 'false').lower() == 'true'

# Check if Supabase credentials are properly defined
try:
    # Try to get the required Supabase configuration values
    SUPABASE_DB_NAME = config('DB_NAME')
    SUPABASE_DB_USER = config('DB_USER')
    SUPABASE_DB_PASSWORD = config('DB_PASSWORD')
    SUPABASE_DB_HOST = config('DB_HOST')

    # Check if any of the required values are empty
    if (SUPABASE_DB_NAME and SUPABASE_DB_USER and SUPABASE_DB_PASSWORD and SUPABASE_DB_HOST and not USE_SQLITE_FOR_MIGRATION):
        # If all required values exist and are not empty, use PostgreSQL
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DB_NAME', 'postgres'),
                'USER': os.getenv('DB_USER', 'postgres'),
                'PASSWORD': os.getenv('ku3nSupabase', ''),
                'HOST': os.getenv('DB_HOST', 'qwpyagbdfmsxyoxanysx.supabase.co'),
                'PORT': os.getenv('DB_PORT', '443'),
                # 'OPTIONS': {
                #     'sslmode': 'require',
                #     'sslrootcert': os.path.join(BASE_DIR, 'ssl', 'prod-ca-2021.crt'),
                },
            }
        # }
        # Add SSL certificate path if specified
        if config('DB_SSL_CERT_PATH', default=''):
            DATABASES['default']['OPTIONS']['sslcert'] = config('DB_SSL_CERT_PATH')
    else:
        # Fallback to SQLite if any credential is missing/empty or if explicitly requested
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
        if not (SUPABASE_DB_NAME and SUPABASE_DB_USER and SUPABASE_DB_PASSWORD and SUPABASE_DB_HOST):
            print("Warning: Supabase credentials not found or incomplete. Using SQLite for now.")
            print("To use Supabase, please fill in your credentials in the .env file.")
except UndefinedValueError:
    # If any Supabase credential is not defined at all, fallback to SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    print("Warning: Supabase credentials not found or incomplete. Using SQLite for now.")
    print("To use Supabase, please fill in your credentials in the .env file.")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Collect static files here

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'mediafiles' # Store user-uploaded media here

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Di bagian ALLOWED_HOSTS
ALLOWED_HOSTS = []

# Tambahkan ini untuk otomatis menangani domain ngrok
if os.environ.get('ENVIRONMENT') != 'production':
    ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])
    # Izinkan semua subdomain ngrok-free.dev
    ALLOWED_HOSTS.append('.ngrok-free.dev')

    CSRF_TRUSTED_ORIGINS = [
    'https://nonidiomatical-teetotally-camron.ngrok-free.dev',
    # tambahkan domain lain jika diperlukan
]